name: docker

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [cli, webhook]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            duyleekun/gitflow-go:${{ matrix.module }}
          build-args: |
            MODULE=${{ matrix.module }}
            VERSION=docker
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}